dataset: 'idc'
dataroot: '/home/bingzhe/dataset/dp'
imageSize: 32
num_classes: 2
image_file_list: '/home/bingzhe/dataset/dp/kfold2/fold_1.txt'
num_folds: 4
data_workers: 16
batch_size: 128
arch: 'AlexNet'
resume: 'exp/normal_alexnet_idc/latest.pth'
experimental_dir: 'exp/normal_alexnet_idc/'
