dataset: 'cifar10'
num_classes: 10
num_folds: 4
data_workers: 16
batch_size: 128
arch: 'BayesLeNetCifar'

log_level: 'INFO'
log_config:
  interval: 50
total_epochs: 100
work_dir: 'exp/bayes_cifarnet'
checkpoint_config:
  interval: 50
resume: False
load_from: None
optimizer:
  type: 'Adam'
  lr: 0.0001
  weight_decay: 0.0000
lr_config:
  policy: 'step'
  step: 20