dataset: 'mnist'
num_classes: 10
num_folds: 4
data_workers: 16
batch_size: 128
arch: 'CryptoNet'

log_level: 'INFO'
log_config:
  interval: 50
total_epochs: 100
work_dir: 'exp/normal_cnet'
checkpoint_config:
  interval: 50
resume: False
load_from: None
optimizer:
  type: 'SGD'
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.00
lr_config:
  policy: 'step'
  step: 20
