dataset: 'mnist'
num_classes: 10
num_folds: 4
data_workers: 16
batch_size: 128
arch: 'LeNet'

log_level: 'INFO'
log_config:
  interval: 50
total_epochs: 100
work_dir: 'exp/sgld_lenet'
checkpoint_config:
  interval: 50
resume: False
load_from: None
optimizer:
  type: 'SGLD'
  lr: 0.0001
  norm_sigma: 0.1
  addnoise: True
lr_config:
  policy: 'step'
  step: 80
