dataset: 'idc'
dataroot: '/home/bingzhe/dataset/dp'
imageSize: 224
num_classes: 2
num_folds: 4
data_workers: 16
batch_size: 128
arch: 'resnet18'

log_level: 'INFO'
log_config:
  interval: 50
total_epochs: 100
work_dir: 'exp/normal_resnet18_idc'
checkpoint_config:
  interval: 50
resume: False
load_from: None
optimizer:
  type: 'SGD'
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.00005
lr_config:
  policy: 'step'
  step: 20
